spring:
  application:
    name: FeedExtra
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/board2024
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    cache:
      disabled: true


    display-request-duration: true
file:
  directory: D:\2024-01\download\greengram_ver4040\